site_name: Staff Engineer's Field Guide
site_description: A comprehensive guide for staff engineers and technical leaders
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.prune
  - navigation.indexes
  - navigation.expand
  - navigation.top
  - navigation.footer
  - toc.integrate
  - toc.follow
  - content.tabs.link
  - content.code.annotate
  - content.action.edit
  - content.action.view
  - content.tooltips
  - search.highlight
  - search.suggest
  - search.share
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: reference/tags.md
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
      combined_output_path: staff-engineers-field-guide.pdf

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - toc
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/homepage.js

nav:
- Home: index.md
- Field Guide:
  - field-guide/intro/index.md
  - Staff Engineer Archetypes:
    - The Tech Lead: field-guide/intro/tech-lead.md
    - The Architect: field-guide/intro/architect.md
    - The Solver: field-guide/intro/solver.md
    - The Right Hand: field-guide/intro/right-hand.md
    - Becoming a Force Multiplier: field-guide/intro/force-multiplier.md
  - Continuous Learning:
    - field-guide/learning/index.md
    - Developing Expertise: field-guide/learning/developing-expertise.md
    - Mentorship & Sponsorship: field-guide/learning/mentorship-sponsorship.md
    - Staying Current: field-guide/learning/staying-current.md
    - The Learning Organization: field-guide/learning/learning-organization.md
    - Teaching to Learn: field-guide/learning/teaching-to-learn.md
  - Engineering Excellence:
    - field-guide/engineering/index.md
    - Site Reliability Engineering: field-guide/engineering/site-reliability-engineering.md
    - Continuous Delivery: field-guide/engineering/continuous-delivery.md
    - CI/CD: field-guide/engineering/cicd.md
    - Test-Driven Development: field-guide/engineering/tdd.md
    - Advanced Testing Strategies: field-guide/engineering/advanced-testing-strategies.md
    - Clean Architecture: field-guide/engineering/clean-architecture.md
    - Evolutionary Architecture: field-guide/engineering/evolutionary-architecture.md
    - Supply Chain Security: field-guide/engineering/supply-chain-security.md
    - Software Supply Chain Security: field-guide/engineering/software-supply-chain-security.md
    - DevOps & Automation: field-guide/engineering/devops.md
    - Git Best Practices: field-guide/engineering/git-practices.md
    - Source Control: field-guide/engineering/source-control.md
    - Code Hygiene & Refactoring: field-guide/engineering/code-hygiene.md
    - Architecture Decision Records: field-guide/engineering/adrs.md
    - Hexagonal Architecture: field-guide/engineering/hexagonal-architecture.md
    - Story Mapping & Splitting: field-guide/engineering/story-mapping.md
    - Chaos Engineering: field-guide/engineering/chaos-engineering.md
  - Critical Thinking:
    - field-guide/thinking/index.md
    - Mental Models for Engineers: field-guide/thinking/mental-models.md
    - Algorithmic Decision-Making: field-guide/thinking/algorithmic-decision-making.md
    - Cognitive Biases: field-guide/thinking/cognitive-biases.md
    - Structured Problem-Solving: field-guide/thinking/structured-problem-solving.md
    - Mind Mapping & Visual Thinking: field-guide/thinking/mind-mapping.md
    - Strategic Thinking: field-guide/thinking/strategic-thinking.md
  - Leadership & Influence:
    - field-guide/leadership/index.md
    - Technical Vision & Purpose: field-guide/leadership/technical-vision.md
    - Influencing Without Authority: field-guide/leadership/influencing-without-authority.md
    - Advanced Conflict Resolution: field-guide/leadership/advanced-conflict-resolution.md
    - Giving & Receiving Feedback: field-guide/leadership/giving-receiving-feedback.md
    - Delivering Difficult Messages: field-guide/leadership/delivering-difficult-messages.md
    - Advanced Mentorship & Career Development: field-guide/leadership/advanced-mentorship-career-development.md
    - Vulnerability in Leadership: field-guide/leadership/vulnerability-leadership.md
    - Self-Awareness & Personality Types: field-guide/leadership/self-awareness-personality-types.md
    - Psychological Safety & Trust: field-guide/leadership/psychological-safety-trust.md
    - Power & Influence in Organizations: field-guide/leadership/power-influence-organizations.md
    - Storytelling for Engineers: field-guide/leadership/storytelling-for-engineers.md
    - Technical Writing for Influence: field-guide/leadership/technical-writing-for-influence.md
    - Presentation & Persuasion Skills: field-guide/leadership/presentation-persuasion-skills.md
    - Working Across Boundaries: field-guide/leadership/working-across-boundaries.md
    - Asynchronous Communication: field-guide/leadership/async-communication.md
    - Navigating Tough Technical Discussions: field-guide/leadership/navigating-tough-technical-discussions.md
  - Teamwork & Collaboration:
    - field-guide/teamwork/index.md
    - Organizational Design: field-guide/teamwork/organizational-design.md
    - Team Formation: field-guide/teamwork/team-formation.md
    - Cultural Transformation & Psychological Safety: field-guide/teamwork/cultural-transformation-psychological-safety.md
    - Five Dysfunctions of a Team: field-guide/teamwork/five-dysfunctions.md
    - Cross-Functional Collaboration: field-guide/teamwork/cross-functional-collaboration.md
    - Mismanagement Agreement: field-guide/teamwork/mismanagement-agreement.md
    - Psychological Safety: field-guide/teamwork/psychological-safety.md
    - The Culture Map: field-guide/teamwork/culture-map.md
  - Execution & Delivery:
    - field-guide/execution/index.md
    - Agile Essentials: field-guide/execution/agile-essentials.md
    - Decision-Making Frameworks: field-guide/execution/decision-making-frameworks.md
    - Strategic Thinking: field-guide/execution/strategic-thinking.md
    - Change Management for Technical Transformations: field-guide/execution/change-management-technical-transformations.md
    - Building a Business Case: field-guide/execution/business-case.md
    - Speed vs. Quality: field-guide/execution/speed-vs-quality.md
    - Navigating Uncertainty & Change: field-guide/execution/navigating-uncertainty.md
    - Prioritization Frameworks: field-guide/execution/prioritization-frameworks.md
    - Organizational Transformation: field-guide/execution/organizational-transformation.md
  - Business Alignment:
    - field-guide/business/index.md
    - Aligning Technology to Business Strategy: field-guide/business/aligning-technology.md
    - Product-Engineering Collaboration: field-guide/business/product-engineering-collaboration.md
    - Engineering Metrics & Business Alignment: field-guide/business/engineering-metrics-business-alignment.md
    - Pitching to Executives: field-guide/business/pitching-to-executives.md
    - Building a Better Business Case: field-guide/business/business-case.md
    - Revenue vs. Risk: field-guide/business/revenue-vs-risk.md
    - Cost Optimization & FinOps: field-guide/business/cost-optimization.md
    - Empowered Teams & Engineering Culture: field-guide/business/empowered-teams.md
  - Engineering Ethics:
    - field-guide/ethics/index.md
    - Bias in Automation: field-guide/ethics/bias-in-automation.md
    - Data Privacy & User Trust: field-guide/ethics/data-privacy.md
    - Ethical Frameworks: field-guide/ethics/ethical-frameworks.md
    - The Ethics of Scale: field-guide/ethics/ethics-of-scale.md
    - Responsible Innovation: field-guide/ethics/responsible-innovation.md
- Reference:
  - Cross-References & Tags: reference/tags.md
  - Patterns & Antipatterns:
    - appendix/antipatterns/index.md
    - appendix/design-patterns/index.md
    - appendix/domain-driven-design/index.md
  - Assessment Tools:
    - appendix/tools/index.md
  - Glossary & Resources:
    - appendix/terms/index.md
    - appendix/laws/index.md
    - appendix/reading/index.md
