site_name: Staff Engineer's Field Guide
site_description: A comprehensive guide for staff engineers and technical leaders
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.indexes
  - toc.integrate
  - content.tabs.link
  - content.code.annotate
  - content.action.edit
  - content.action.view
plugins:
  - search
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
      combined_output_path: staff-engineers-field-guide.pdf

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - toc
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
- Home: index.md
- Field Guide:
  - Introduction:
    - Introduction: field-guide/intro/index.md
    - The Tech Lead: field-guide/intro/tech-lead.md
    - The Architect: field-guide/intro/architect.md
    - The Solver: field-guide/intro/solver.md
    - The Right Hand: field-guide/intro/right-hand.md
    - Becoming a Force Multiplier: field-guide/intro/force-multiplier.md
  - Learning:
    - Introduction: field-guide/learning/index.md
    - Developing Expertise: field-guide/learning/developing-expertise.md
    - Mentorship & Sponsorship: field-guide/learning/mentorship-sponsorship.md
    - Staying Current: field-guide/learning/staying-current.md
    - The Learning Organization: field-guide/learning/learning-organization.md
    - Teaching to Learn: field-guide/learning/teaching-to-learn.md
  - Engineering:
    - Introduction: field-guide/engineering/index.md
    - Site Reliability Engineering: field-guide/engineering/site-reliability-engineering.md
    - Continuous Delivery: field-guide/engineering/continuous-delivery.md
    - CI/CD: field-guide/engineering/cicd.md
    - Test-Driven Development: field-guide/engineering/tdd.md
    - Advanced Testing Strategies: field-guide/engineering/advanced-testing-strategies.md
    - Clean Architecture: field-guide/engineering/clean-architecture.md
    - Evolutionary Architecture: field-guide/engineering/evolutionary-architecture.md
    - Supply Chain Security: field-guide/engineering/supply-chain-security.md
    - Software Supply Chain Security: field-guide/engineering/software-supply-chain-security.md
    - DevOps & Automation: field-guide/engineering/devops.md
    - Git Best Practices: field-guide/engineering/git-practices.md
    - Source Control: field-guide/engineering/source-control.md
    - Code Hygiene & Refactoring: field-guide/engineering/code-hygiene.md
    - Architecture Decision Records: field-guide/engineering/adrs.md
    - Hexagonal Architecture: field-guide/engineering/hexagonal-architecture.md
    - Story Mapping & Splitting: field-guide/engineering/story-mapping.md
    - Chaos Engineering: field-guide/engineering/chaos-engineering.md
  - Critical Thinking:
    - Introduction: field-guide/thinking/index.md
    - Mental Models for Engineers: field-guide/thinking/mental-models.md
    - Algorithmic Decision-Making: field-guide/thinking/algorithmic-decision-making.md
    - Cognitive Biases: field-guide/thinking/cognitive-biases.md
    - Structured Problem-Solving: field-guide/thinking/structured-problem-solving.md
    - Mind Mapping & Visual Thinking: field-guide/thinking/mind-mapping.md
    - Strategic Thinking: field-guide/thinking/strategic-thinking.md
  - Leadership:
    - Introduction: field-guide/leadership/index.md
    - Technical Vision & Purpose: field-guide/leadership/technical-vision.md
    - Influencing Without Authority: field-guide/leadership/influencing-without-authority.md
    - Advanced Conflict Resolution: field-guide/leadership/advanced-conflict-resolution.md
    - Giving & Receiving Feedback: field-guide/leadership/giving-receiving-feedback.md
    - Delivering Difficult Messages: field-guide/leadership/delivering-difficult-messages.md
    - Advanced Mentorship & Career Development: field-guide/leadership/advanced-mentorship-career-development.md
    - Vulnerability in Leadership: field-guide/leadership/vulnerability-leadership.md
    - Self-Awareness & Personality Types: field-guide/leadership/self-awareness-personality-types.md
    - Psychological Safety & Trust: field-guide/leadership/psychological-safety-trust.md
    - Power & Influence in Organizations: field-guide/leadership/power-influence-organizations.md
    - Storytelling for Engineers: field-guide/leadership/storytelling-for-engineers.md
    - Technical Writing for Influence: field-guide/leadership/technical-writing-for-influence.md
    - Presentation & Persuasion Skills: field-guide/leadership/presentation-persuasion-skills.md
    - Working Across Boundaries: field-guide/leadership/working-across-boundaries.md
    - Asynchronous Communication: field-guide/leadership/async-communication.md
    - Navigating Tough Technical Discussions: field-guide/leadership/navigating-tough-technical-discussions.md
  - Teamwork:
    - Introduction: field-guide/teamwork/index.md
    - Organizational Design: field-guide/teamwork/organizational-design.md
    - Team Formation: field-guide/teamwork/team-formation.md
    - Cultural Transformation & Psychological Safety: field-guide/teamwork/cultural-transformation-psychological-safety.md
    - Five Dysfunctions of a Team: field-guide/teamwork/five-dysfunctions.md
    - Cross-Functional Collaboration: field-guide/teamwork/cross-functional-collaboration.md
    - Mismanagement Agreement: field-guide/teamwork/mismanagement-agreement.md
    - Psychological Safety: field-guide/teamwork/psychological-safety.md
    - The Culture Map: field-guide/teamwork/culture-map.md
  - Execution:
    - Introduction: field-guide/execution/index.md
    - Agile Essentials: field-guide/execution/agile-essentials.md
    - Decision-Making Frameworks: field-guide/execution/decision-making-frameworks.md
    - Strategic Thinking: field-guide/execution/strategic-thinking.md
    - Change Management for Technical Transformations: field-guide/execution/change-management-technical-transformations.md
    - Building a Business Case: field-guide/execution/business-case.md
    - Speed vs. Quality: field-guide/execution/speed-vs-quality.md
    - Navigating Uncertainty & Change: field-guide/execution/navigating-uncertainty.md
    - Prioritization Frameworks: field-guide/execution/prioritization-frameworks.md
    - Organizational Transformation: field-guide/execution/organizational-transformation.md
  - Business:
    - Introduction: field-guide/business/index.md
    - Aligning Technology to Business Strategy: field-guide/business/aligning-technology.md
    - Product-Engineering Collaboration: field-guide/business/product-engineering-collaboration.md
    - Engineering Metrics & Business Alignment: field-guide/business/engineering-metrics-business-alignment.md
    - Pitching to Executives: field-guide/business/pitching-to-executives.md
    - Building a Better Business Case: field-guide/business/business-case.md
    - Revenue vs. Risk: field-guide/business/revenue-vs-risk.md
    - Cost Optimization & FinOps: field-guide/business/cost-optimization.md
    - Empowered Teams & Engineering Culture: field-guide/business/empowered-teams.md
  - Ethics:
    - Introduction: field-guide/ethics/index.md
    - Bias in Automation: field-guide/ethics/bias-in-automation.md
    - Data Privacy & User Trust: field-guide/ethics/data-privacy.md
    - Ethical Frameworks: field-guide/ethics/ethical-frameworks.md
    - The Ethics of Scale: field-guide/ethics/ethics-of-scale.md
    - Responsible Innovation: field-guide/ethics/responsible-innovation.md
- Appendix:
  - Antipatterns:
    - Overview: appendix/antipatterns/index.md
    - 'Antipatterns: Recognizing and Avoiding Design Missteps': appendix/antipatterns/antipatterns-overview.md
    - 'Assumption Driven Programming: Building Software for *Everyone*': appendix/antipatterns/assumption-driven-programming.md
    - 'The Big Ball of Mud: A Critical Architectural Anti-Pattern': appendix/antipatterns/big-ball-of-mud.md
    - 'The Blob: A Dangerous Growth Pattern': appendix/antipatterns/blob.md
    - 'Broken Windows: Maintaining Code Health Through Consistent Small Actions': appendix/antipatterns/broken-windows.md
    - 'The Calendar Coder: A Cargo Cult in Software Development': appendix/antipatterns/calendar-coder.md
    - 'Code Smells: Recognizing and Addressing Problems in Your Code': appendix/antipatterns/code-smells.md
    - 'Copy Folder Versioning: A Critical Anti-Pattern': appendix/antipatterns/copy-folder-versioning.md
    - 'Copy-Paste Programming: A Critical Anti-Pattern': appendix/antipatterns/copy-paste-programming.md
    - 'Death by Planning: Prioritizing Velocity Over Detailed Roadmaps': appendix/antipatterns/death-by-planning.md
    - 'Death March: Recognizing and Mitigating the Symptoms of Unsustainable Projects': appendix/antipatterns/death-march.md
    - 'The Duct Tape Coder: A Critical Examination of Expedient Software': appendix/antipatterns/duct-tape-coder.md
    - 'Exposing Collection Properties: A Critical Review': appendix/antipatterns/exposing-collection-properties.md
    - 'Fast Beats Right: The Cost of Speeding Through Quality': appendix/antipatterns/fast-beats-right.md
    - 'Feature Creep: Understanding and Mitigating Scope Expansion in Software Development': appendix/antipatterns/feature-creep.md
    - 'Flags Over Objects: A Deep Dive into a Critical Code Smell': appendix/antipatterns/flags-over-objects.md
    - The Perilous Practice of "Found on the Internet" Code: appendix/antipatterns/found-on-internet.md
    - 'Frankencode: The Frankenstein of Software Systems': appendix/antipatterns/frankencode.md
    - 'The Golden Hammer: Avoiding Technological Lock-In': appendix/antipatterns/golden-hammer.md
    - 'Iceberg Classes: Understanding and Avoiding Deeply Encapsulated Classes': appendix/antipatterns/iceberg-class.md
    - 'Eliminating Magic Strings: A Critical Architectural Pattern': appendix/antipatterns/magic-strings.md
    - 'Mushroom Management: Why Lack of Transparency Undermines Software Development': appendix/antipatterns/mushroom-management.md
    - 'Not Invented Here (NIH): The Cost of Blind Innovation': appendix/antipatterns/not-invented-here.md
    - 'One Thing To Rule Them All: Understanding the Anti-Pattern': appendix/antipatterns/one-thing-to-rule-them-all.md
    - 'Reinventing the Wheel: A Critical Examination': appendix/antipatterns/reinventing-the-wheel.md
    - 'The Shiny Toy Anti-Pattern: A Critical Defense Against Technological Momentum': appendix/antipatterns/shiny-toy.md
    - 'Smoke and Mirrors: The Peril of Unrealistic Customer Expectations': appendix/antipatterns/smoke-and-mirrors.md
    - 'Spaghetti Code: A Systemic Threat to Maintainability and Scalability': appendix/antipatterns/spaghetti-code.md
    - 'Static Cling: Avoiding Unnecessary Coupling': appendix/antipatterns/static-cling.md
    - 'Walking Through a Minefield: The Cost of Premature Release': appendix/antipatterns/walking-through-a-minefield.md
    - 'Understanding the Waterfall Model: A Critical Examination': appendix/antipatterns/waterfall.md
  - Design Patterns:
    - Overview: appendix/design-patterns/index.md
    - 'Adapter Design Pattern: Bridging the Gap Between Incompatible Interfaces': appendix/design-patterns/adapter-design-pattern.md
    - 'The Builder Design Pattern: Constructing Complex Objects with Control': appendix/design-patterns/builder-pattern.md
    - 'Design Patterns: A Practical Guide for Engineers': appendix/design-patterns/design-patterns-overview.md
    - 'Guard Clauses: Defensive Programming for Clarity and Robustness': appendix/design-patterns/guard-clause.md
    - 'The Null Object Pattern: A Robust Strategy for Handling Missing Data': appendix/design-patterns/null-object-pattern.md
    - Repository Pattern: appendix/design-patterns/repository-pattern.md
    - 'The REPR Design Pattern: A Streamlined Approach to API Development': appendix/design-patterns/repr-design-pattern.md
    - 'Mastering the Singleton Pattern: A Deep Dive for Staff Engineers': appendix/design-patterns/singleton.md
    - 'The Specification Pattern: A Robust Approach to Querying and Filtering Data': appendix/design-patterns/specification-pattern.md
    - State Design Pattern: appendix/design-patterns/state-design-pattern.md
    - Strategy Pattern: appendix/design-patterns/strategy-pattern.md
  - Domain Driven Design:
    - Overview: appendix/domain-driven-design/index.md
    - Aggregate Pattern: appendix/domain-driven-design/aggregate-pattern.md
    - 'The Anemic Domain Model: A Critical Design Flaw': appendix/domain-driven-design/anemic-model.md
    - 'Anti-Corruption Layers: Protecting Your Domain Model': appendix/domain-driven-design/anti-corruption-layer.md
    - 'Domain-Driven Design: Building Software That Aligns with Reality': appendix/domain-driven-design/ddd-overview.md
    - 'Understanding Entities: Core Concepts for Robust Systems': appendix/domain-driven-design/entity.md
    - 'Ubiquitous Language: The Foundation of Reliable Software': appendix/domain-driven-design/ubiquitous-language.md
    - 'Value Objects: Representing Concepts with Immutable Data': appendix/domain-driven-design/value-object.md
  - Laws:
    - Overview: appendix/laws/index.md
    - Understanding and Applying Murphy's Law in Systems Engineering: appendix/laws/murphys-law.md
  - Terms:
    - Overview: appendix/terms/index.md
    - Understanding and Mitigating the Bus Factor: appendix/terms/bus-factor.md
    - 'Understanding Technical Debt: A Strategic Approach': appendix/terms/technical-debt.md
  - Tools:
    - Overview: appendix/tools/index.md
    - 'Staff Engineer Competency Assessment': appendix/tools/staff-engineer-competency-assessment.md
    - 'Team Health Diagnostic': appendix/tools/team-health-diagnostic.md
    - 'Development Tracking System': appendix/tools/development-tracking-system.md
    - 'Engineering Excellence Assessment Framework': appendix/tools/engineering-excellence-assessment.md
    - 'Critical Thinking Assessment': appendix/tools/critical-thinking-assessment.md
    - 'Technical Debt Management Framework': appendix/tools/technical-debt-management-framework.md
    - 'Team Topology Assessment Framework': appendix/tools/team-topology-assessment.md
  - Recommended Reading:
    - Overview: appendix/reading/index.md
