site_name: Staff Engineer's Field Guide
site_description: A comprehensive guide for staff engineers and technical leaders
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.indexes
  - toc.integrate
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
- Home: index.md
- Field Guide:
  - Introduction: field-guide/index.md
  - Leadership:
    - Introduction: field-guide/leadership/index.md
    - Influencing Without Authority: field-guide/leadership/influencing-without-authority.md
    - Vulnerability in Leadership: field-guide/leadership/vulnerability-leadership.md
    - Self-Awareness & Personality Types: field-guide/leadership/self-awareness-personality-types.md
    - Giving & Receiving Feedback: field-guide/leadership/giving-receiving-feedback.md
    - Delivering Difficult Messages: field-guide/leadership/delivering-difficult-messages.md
    - Psychological Safety & Trust: field-guide/leadership/psychological-safety-trust.md
    - Power & Influence in Organizations: field-guide/leadership/power-influence-organizations.md
    - Storytelling for Engineers: field-guide/leadership/storytelling-for-engineers.md
    - Technical Writing for Influence: field-guide/leadership/technical-writing-for-influence.md
    - Presentation & Persuasion Skills: field-guide/leadership/presentation-persuasion-skills.md
    - Working Across Boundaries: field-guide/leadership/working-across-boundaries.md
    - Asynchronous Communication: field-guide/leadership/async-communication.md
    - Navigating Tough Technical Discussions: field-guide/leadership/navigating-tough-technical-discussions.md
  - Teamwork:
    - Introduction: field-guide/teamwork/index.md
    - Team Formation: field-guide/teamwork/team-formation.md
    - Five Dysfunctions of a Team: field-guide/teamwork/five-dysfunctions.md
    - Cross-Functional Collaboration: field-guide/teamwork/cross-functional-collaboration.md
    - Mismanagement Agreement: field-guide/teamwork/mismanagement-agreement.md
    - Psychological Safety: field-guide/teamwork/psychological-safety.md
    - The Culture Map: field-guide/teamwork/culture-map.md
  - Execution:
    - Introduction: field-guide/execution/index.md
    - Agile Essentials: field-guide/execution/agile-essentials.md
    - Decision-Making Frameworks: field-guide/execution/decision-making-frameworks.md
    - Building a Business Case: field-guide/execution/business-case.md
    - Strategic Thinking: field-guide/execution/strategic-thinking.md
    - Speed vs. Quality: field-guide/execution/speed-vs-quality.md
    - Navigating Uncertainty & Change: field-guide/execution/navigating-uncertainty.md
    - Prioritization Frameworks: field-guide/execution/prioritization-frameworks.md
    - Organizational Transformation: field-guide/execution/organizational-transformation.md
  - Engineering:
    - Introduction: field-guide/engineering/index.md
    - CI/CD: field-guide/engineering/cicd.md
    - Git Best Practices: field-guide/engineering/git-practices.md
    - DevOps & Automation: field-guide/engineering/devops.md
    - Supply Chain Security: field-guide/engineering/supply-chain-security.md
    - Test-Driven Development: field-guide/engineering/tdd.md
    - Code Hygiene & Refactoring: field-guide/engineering/code-hygiene.md
    - Architecture Decision Records: field-guide/engineering/adrs.md
    - Hexagonal Architecture: field-guide/engineering/hexagonal-architecture.md
    - Story Mapping & Splitting: field-guide/engineering/story-mapping.md
    - Bias in Automation: field-guide/engineering/bias-in-automation.md
    - Software Supply Chain Security: field-guide/engineering/software-supply-chain-security.md
    - Source Control: field-guide/engineering/source-control.md
    - Chaos Engineering: field-guide/engineering/chaos-engineering.md
  - Critical Thinking:
    - Introduction: field-guide/thinking/index.md
    - Mental Models for Engineers: field-guide/thinking/mental-models.md
    - Cognitive Biases: field-guide/thinking/cognitive-biases.md
    - Structured Problem-Solving: field-guide/thinking/structured-problem-solving.md
    - Mind Mapping & Visual Thinking: field-guide/thinking/mind-mapping.md
    - Strategic Thinking: field-guide/thinking/strategic-thinking.md
  - Business:
    - Introduction: field-guide/business/index.md
    - Aligning Technology to Business Strategy: field-guide/business/aligning-technology.md
    - Pitching to Executives: field-guide/business/pitching-to-executives.md
    - Building a Better Business Case: field-guide/business/business-case.md
    - Revenue vs. Risk: field-guide/business/revenue-vs-risk.md
    - Cost Optimization & FinOps: field-guide/business/cost-optimization.md
    - Empowered Teams & Engineering Culture: field-guide/business/empowered-teams.md
- Appendix:
  - Antipatterns:
    - Overview: antipatterns/index.md
    - 'Antipatterns: Recognizing and Avoiding Design Missteps': antipatterns/antipatterns-overview.md
    - 'Assumption Driven Programming: Building Software for *Everyone*': antipatterns/assumption-driven-programming.md
    - 'The Big Ball of Mud: A Critical Architectural Anti-Pattern': antipatterns/big-ball-of-mud.md
    - 'The Blob: A Dangerous Growth Pattern': antipatterns/blob.md
    - 'Broken Windows: Maintaining Code Health Through Consistent Small Actions': antipatterns/broken-windows.md
    - 'The Calendar Coder: A Cargo Cult in Software Development': antipatterns/calendar-coder.md
    - 'Code Smells: Recognizing and Addressing Problems in Your Code': antipatterns/code-smells.md
    - 'Copy Folder Versioning: A Critical Anti-Pattern': antipatterns/copy-folder-versioning.md
    - 'Copy-Paste Programming: A Critical Anti-Pattern': antipatterns/copy-paste-programming.md
    - 'Death by Planning: Prioritizing Velocity Over Detailed Roadmaps': antipatterns/death-by-planning.md
    - 'Death March: Recognizing and Mitigating the Symptoms of Unsustainable Projects': antipatterns/death-march.md
    - 'The Duct Tape Coder: A Critical Examination of Expedient Software': antipatterns/duct-tape-coder.md
    - 'Exposing Collection Properties: A Critical Review': antipatterns/exposing-collection-properties.md
    - 'Fast Beats Right: The Cost of Speeding Through Quality': antipatterns/fast-beats-right.md
    - 'Feature Creep: Understanding and Mitigating Scope Expansion in Software Development': antipatterns/feature-creep.md
    - 'Flags Over Objects: A Deep Dive into a Critical Code Smell': antipatterns/flags-over-objects.md
    - The Perilous Practice of "Found on the Internet" Code: antipatterns/found-on-internet.md
    - 'Frankencode: The Frankenstein of Software Systems': antipatterns/frankencode.md
    - 'The Golden Hammer: Avoiding Technological Lock-In': antipatterns/golden-hammer.md
    - 'Iceberg Classes: Understanding and Avoiding Deeply Encapsulated Classes': antipatterns/iceberg-class.md
    - 'Eliminating Magic Strings: A Critical Architectural Pattern': antipatterns/magic-strings.md
    - 'Mushroom Management: Why Lack of Transparency Undermines Software Development': antipatterns/mushroom-management.md
    - 'Not Invented Here (NIH): The Cost of Blind Innovation': antipatterns/not-invented-here.md
    - 'One Thing To Rule Them All: Understanding the Anti-Pattern': antipatterns/one-thing-to-rule-them-all.md
    - 'Reinventing the Wheel: A Critical Examination': antipatterns/reinventing-the-wheel.md
    - 'The Shiny Toy Anti-Pattern: A Critical Defense Against Technological Momentum': antipatterns/shiny-toy.md
    - 'Smoke and Mirrors: The Peril of Unrealistic Customer Expectations': antipatterns/smoke-and-mirrors.md
    - 'Spaghetti Code: A Systemic Threat to Maintainability and Scalability': antipatterns/spaghetti-code.md
    - 'Static Cling: Avoiding Unnecessary Coupling': antipatterns/static-cling.md
    - 'Walking Through a Minefield: The Cost of Premature Release': antipatterns/walking-through-a-minefield.md
    - 'Understanding the Waterfall Model: A Critical Examination': antipatterns/waterfall.md
  - Design Patterns:
    - Overview: design-patterns/index.md
    - 'Adapter Design Pattern: Bridging the Gap Between Incompatible Interfaces': design-patterns/adapter-design-pattern.md
    - 'The Builder Design Pattern: Constructing Complex Objects with Control': design-patterns/builder-pattern.md
    - 'Design Patterns: A Practical Guide for Engineers': design-patterns/design-patterns-overview.md
    - 'Guard Clauses: Defensive Programming for Clarity and Robustness': design-patterns/guard-clause.md
    - 'The Null Object Pattern: A Robust Strategy for Handling Missing Data': design-patterns/null-object-pattern.md
    - Repository Pattern: design-patterns/repository-pattern.md
    - 'The REPR Design Pattern: A Streamlined Approach to API Development': design-patterns/repr-design-pattern.md
    - 'Mastering the Singleton Pattern: A Deep Dive for Staff Engineers': design-patterns/singleton.md
    - 'The Specification Pattern: A Robust Approach to Querying and Filtering Data': design-patterns/specification-pattern.md
    - State Design Pattern: design-patterns/state-design-pattern.md
    - Strategy Pattern: design-patterns/strategy-pattern.md
  - Domain Driven Design:
    - Overview: domain-driven-design/index.md
    - Aggregate Pattern: domain-driven-design/aggregate-pattern.md
    - 'The Anemic Domain Model: A Critical Design Flaw': domain-driven-design/anemic-model.md
    - 'Anti-Corruption Layers: Protecting Your Domain Model': domain-driven-design/anti-corruption-layer.md
    - 'Domain-Driven Design: Building Software That Aligns with Reality': domain-driven-design/ddd-overview.md
    - 'Understanding Entities: Core Concepts for Robust Systems': domain-driven-design/entity.md
    - 'Ubiquitous Language: The Foundation of Reliable Software': domain-driven-design/ubiquitous-language.md
    - 'Value Objects: Representing Concepts with Immutable Data': domain-driven-design/value-object.md
  - Laws:
    - Overview: laws/index.md
    - 'Cunningham''s Law: The Paradox of Online Collaboration': laws/cunninghams-law.md
    - 'Laws of Software Development: A Deep Dive for Staff Engineers': laws/laws-overview.md
    - Understanding and Applying Murphy's Law in Systems Engineering: laws/murphys-law.md
  - Terms:
    - Overview: terms/index.md
    - Understanding and Mitigating the Bus Factor: terms/bus-factor.md
    - Kinds of Models in Application Architecture: terms/kinds-of-models.md
    - 'Understanding Technical Debt: A Strategic Approach': terms/technical-debt.md
  - Tools:
    - Overview: tools/index.md
    - 'Understanding Build Servers: The Foundation of Reliable Software Delivery': tools/build-server.md
    - 'Version Control: A Foundation for Reliable Software Development': tools/version-control.md
  - Values:
    - Overview: values/index.md
    - Mastering Communication in Software Development: values/communication.md
    - Cultivating Courage in High-Performing Software Teams: values/courage.md
    - 'Feedback: The Engine of Continuous Improvement': values/feedback.md
    - 'Cultivating Respect: A Foundation for High-Performing Teams': values/respect.md
    - 'Simplicity: The Foundation of Robust Systems': values/simplicity.md
    - Understanding and Applying Extreme Programming Values: values/values-overview.md
